class AuthError(Exception):
    pass


class OAuth2Error(Exception):
    pass
